### PR TITLE
Fix Right Click Help lookup not always working.

### LINKED ISSUE #1740: Right-click Get Help for Command returns help for Get-Help cmdlet
## Issue Description ##

_Get Help for Command_ in right-click menu has different behaviour then command bar _PowerShell: Get Help for Command_.

The right-click menu gets online help for the `Get-Help` cmdlet. Where as the command bar actually returns the online help for the specified cmdlet under the cursor.

## Attached Logs ##

[logs.zip](https://github.com/PowerShell/vscode-powershell/files/2816314/logs.zip)

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.17763 |
| VSCode | 1.30.2|
| PowerShell Extension Version | 1.11.0 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|5.1.17763.134|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.17763.134|
|BuildVersion|10.0.17763.134|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|azure-pipelines|ms-azure-devops|1.147.1|
|code-spell-checker|streetsidesoftware|1.6.10|
|DocFX|ms-docfx|0.1.3|
|docs-article-templates|docsmsft|0.1.4|
|docs-authoring-pack|docsmsft|0.1.1|
|docs-markdown|docsmsft|0.2.2|
|docs-preview|docsmsft|0.3.16|
|github-issues-prs|ms-vscode|0.9.1|
|gitlens|eamodio|9.4.1|
|PowerShell|ms-vscode|1.11.0|
|vscode-markdownlint|DavidAnson|0.23.0|
|vscode-pull-request-github|GitHub|0.3.2|
|vscode-yaml|redhat|0.2.1|;

</details>

### PR DESCRIPTION
**Pull request by corbob**
## PR Summary
Fixes #1740

When selecting Show Help from right click menu, vscode is sending the editor information through the item parameter. The editor doesn't have a Name property, so we should check that the item being passed has a Name property as well.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- NA PR has tests
- [x] This PR is ready to merge and is not work in progress

### CODE REVIEW

File: src/features/ShowHelp.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export class ShowHelpFeature implements IFeature {
                     "Unable to instantiate; language client undefined.");
                 return;
             }
-            if (item === undefined) {
+            if (item === undefined || !item.hasOwnProperty("Name")) {
```
Comment (rkeithhill) [inline src/features/ShowHelp.ts]: Do we need to consider the scenario where the Name property exists but its value is undefined?

Comment (corbob) [reply src/features/ShowHelp.ts]: yeah, that will work better. I think when I was testing it out in Chrome console it was erroring out when Name wasn't there. However, I've changed it to just test for undefined and it doesn't seem to have an issue. I'll get this changed to just test if it's undefined.

Chrome being Chrome...

Comment (TylerLeonhardt) [reply src/features/ShowHelp.ts]: You can just use a truthy chech:

```suggestion
            if (!item || !item.Name) {
```

Comment (corbob) [reply src/features/ShowHelp.ts]: This Suggested Change feature is awesome. Being able to take that change and commit it from the browser 👌 

I also figured out why my Chrome console stuff was erroring out, I wasn't defining the variable beforehand.

Comment (TylerLeonhardt) [reply src/features/ShowHelp.ts]: Just make sure you test the change :)

Comment (corbob) [reply src/features/ShowHelp.ts]: yup, it works as expected 😃
