### PR TITLE
Adds option to generate a bug report in GitHub

### LINKED ISSUE #820: Add a "Report a problem on GitHub" command that automates filing a bug on GitHub
We need a command that will make it super easy for users to file new issues on GitHub so that they don't have to manually gather details on versions and environment information.  I imagine this will be a combination of TypeScript and PowerShell code.  @rkeithhill has started some of the PowerShell side code [in PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices/blob/master/module/PowerShellEditorServices/PowerShellEditorServices.psm1#L137).

You can see how VS Code generates their issue data here:

https://github.com/Microsoft/vscode/blob/f1f3f60e300abae4055a2a9fe3c40c63be5a8e82/src/vs/workbench/electron-browser/actions.ts#L704

@PowerSchill has expressed an interest in working on this :)

### PR DESCRIPTION
**Pull request by PowerSchill**
This pull request adds the ability to generate a bug report for the extension by collecting operating system, vscode, and PowerShell information and inserting it into a new GitHub issues entry. 

 Key Points:
 * The project to generate the issue in is configurable and can be set in the settings. It defaults to the main PowerShell repository.
 * Log files are *not* handled with this submission. However attempting to facilitate the inclusion of log files is still desired. 

 This PR will resolve #820. 

**Below is an example output**

## Issue Description ##

I am experiencing a problem with...

## Attached Logs ##

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell#reporting-problems) about capturing and sending logs.

### Visual Studio Code ###

| Name | Version |
| --- | --- |
| Operating System | Darwin x64 16.6.0 |
| VSCode | 1.15.0-insider|
| PowerShell Extension Version | 1.4.1 |

### PowerShell Information ###

|Name|Value|
|---|---|
|PSVersion|6.0.0-beta|
|PSEdition|Core|
|BuildVersion|3.0.0.0|
|CLRVersion||
|GitCommitId|v6.0.0-beta.2|
|OS|Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017, root:xnu-3789.60.24~6/RELEASE_X86_64|
|Platform|Unix|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|

### Visual Studio Code Extensions ###

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.2|
|bracketselection|guosong|1.0.3|
|Chef|Pendrica|0.6.3|
|code-settings-sync|Shan|2.8.2|
|copy-github-url|mattlott|0.1.0|
|copy-markdown-as-html|jerriepelser|1.0.0|
|csharp|ms-vscode|1.11.0|
|fontsize-shortcuts|peterjuras|1.3.0|
|gc-excelviewer|GrapeCity|1.1.15|
|githistory|donjayamanne|0.2.1|
|gitignore|codezombiech|0.5.0|
|gitlens|eamodio|4.3.1|
|indenticator|SirTori|0.4.2|
|licenser|ymotongpoo|1.0.1|
|markdown-shortcuts|mdickin|0.8.1|
|markdown-toc|AlanWalk|1.5.5|
|path-intellisense|christian-kohler|1.4.2|
|PowerShell|ms-vscode|1.4.1|
|prettify-json|mohsen1|0.0.3|
|sublime-keybindings|ms-vscode|2.9.1|
|theme-sapphire|Tyriar|0.2.1|
|todotasks|sandy081|0.5.0|
|tslint|eg2|0.16.0|
|vscode-gist|dbankier|0.5.3|
|vscode-icons|robertohuertasm|7.10.1|
|vscode-markdownlint|DavidAnson|0.9.1|
|vscode-paste-image|mushan|0.9.4|
|vscode-table-formatter|shuworks|1.1.2|
|vscode-todo-parser|minhthai|1.9.0|;

</details>

### CODE REVIEW

File: src/features/GenerateBugReport.ts [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+export class GenerateBugReportFeature implements IFeature {
+
+    private command: vscode.Disposable;
+    private powerShellProcess: cp.ChildProcess;
+
+    constructor(private sessionManager: SessionManager) {
+        this.command = vscode.commands.registerCommand('PowerShell.GenerateBugReport', () => {
+
+
+            var OutputChannel = window.createOutputChannel('Debug');
```
Comment (daviwil) [inline src/features/GenerateBugReport.ts]: You can use the ILogger interface for this instead of an output channel, it'll go to the PowerShell Extension Logs channel.

Comment (PowerSchill) [inline src/features/GenerateBugReport.ts]: No, actually that was just used for debugging my code. I will remove it. Unless you think it would be beneficial to put the information into the log file.

**Comment by daviwil** [comment]
Thanks again for doing this, Mark!  Sorry it took me so long to get it merged :)
