### PR TITLE
`Restart Current Session` in every session quick pick

### LINKED ISSUE #1614: No option to restart session in some instances
### Issue Description

There are times that PowerShell session will crash. Normally you can restart it but there are instances where it won't allow you too. 

image

The status in the bottom:

image

Most likely it happens when you are told that session crashed, it asks you if you want to restart it, you respond no, and there is no option to "start" it again. 

#### Expected Behaviour

Ability to restart the session, always.

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
## PR Summary

fixes #1614 

This does some reorganizing of the quick pick dialog for sessions. It makes sure the `Restart Current Session` command is always available and only shows the `Switch to X` when a session is running.

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

File: src/session.ts [hunk 1]
```diff
@@ -755,26 +764,22 @@ export class SessionManager implements Middleware {
...
-            availablePowerShellExes
-                .filter((item) => item.exePath.toLowerCase() !== currentExePath)
-                .map((item) => {
-                    return new SessionMenuItem(
-                        `Switch to ${item.versionName}`,
-                        () => { this.changePowerShellExePath(item.exePath); });
-                });
-
-        menuItems = menuItems.concat(powerShellItems);
-
```
Comment (SeeminglyScience) [inline src/session.ts]: I'd like to keep the `Switch to` options with a failed session if that's not too much trouble.  It's useful when testing features that may fail immediately in either Core or Full early on in the development process.  I used it a few times early on when working on PSRL before I figured out the module resolution issues.

File: src/session.ts [hunk 2]
```diff
@@ -747,6 +747,15 @@ export class SessionManager implements Middleware {
                     `(${this.versionDetails.architecture}) ${this.versionDetails.edition} Edition ` +
                     `[${this.versionDetails.version}]`;
 
+            const powerShellItems =
```
Comment (rjmholt) [inline src/session.ts]: Nice!

File: src/session.ts [hunk 3]
```diff
@@ -755,26 +764,22 @@ export class SessionManager implements Middleware {
                 new SessionMenuItem(
                     "Restart Current Session",
                     () => { this.restartSession(); }),
+
+                ...powerShellItems,
```
Comment (rjmholt) [inline src/session.ts]: I dislike how easy it is to miss this syntax (especially in a list with two other new objects), but I don't really have a serious complaint. It's idiomatic and I'll come to like it I'm sure.

File: src/session.ts [hunk 4]
```diff
@@ -755,26 +764,22 @@ export class SessionManager implements Middleware {
...
             ];
+
         } else if (this.sessionStatus === SessionStatus.Failed) {
             menuItems = [
                 new SessionMenuItem(
                     `Session initialization failed, click here to show PowerShell extension logs`,
                     () => { vscode.commands.executeCommand("PowerShell.ShowLogs"); }),
+
+                new SessionMenuItem(
```
Comment (rjmholt) [inline src/session.ts]: This is in the above block too. Maybe it should just be there in all cases (outside the `if`/`else`)?

File: src/session.ts (hunk 1 above)
Comment (TylerLeonhardt) [reply src/session.ts]: added back 😃

File: src/session.ts (hunk 2 above)
Comment (TylerLeonhardt) [reply src/session.ts]: 👍

File: src/session.ts (hunk 3 above)
Comment (TylerLeonhardt) [reply src/session.ts]: I've added a comment so it's a little bit clearer 🙂

File: src/session.ts (hunk 4 above)
Comment (TylerLeonhardt) [reply src/session.ts]: big refactor since the last commit. This is addressed now.

File: src/session.ts [hunk 5]
```diff
@@ -729,12 +729,11 @@ export class SessionManager implements Middleware {
     }
 
     private showSessionMenu() {
-        let menuItems: SessionMenuItem[] = [];
-
         const currentExePath = (this.powerShellExePath || "").toLowerCase();
         const availablePowerShellExes =
             getAvailablePowerShellExes(this.platformDetails, this.sessionSettings);
 
+        let sessionText: string;
```
[the remark this answers is not in the document]
Comment (TylerLeonhardt) [reply src/session.ts]: exhaustive switch statements FTW 👍 updated to a switch.
