### PR TITLE
Make SaveAs work for untitled files

### LINKED ISSUE #1303: CurrentFile.SaveAs() doesn't work for untitled files
If an untitled file is opened and the language mode changed to PowerShell, trying to SaveAs() will silently do nothing because the first thing we do is [check for the file path](https://github.com/PowerShell/vscode-powershell/blob/ab5ee300b37c3f5fe2c4a83e0370d8b92d628822/src/features/ExtensionCommands.ts#L394). Untitled URIs fail this test, so just do nothing.

We should instead recognise untitled URIs and save them relative to the workspace root (or if an absolute path is given, just save it there).

Thanks to @ brwilkinson to pointing this issue out.

### PR DESCRIPTION
**Pull request by rjmholt**
Fixes #1303.

This makes the `$psEditor.GetEditorContext().CurrentFile.SaveAs("blah.ps1")` function work for files with an untitled schema.

It also adds some logging to make it more diagnosable (because the logic for dealing with VSCode's crazy URIs is a bit hairy).

Some cases to test (on various platforms) before we merge:
- [x] Take a normal powershell file, modify it and `Save()`
- [x] Take a normal powershell file, modify it and `SaveAs()` with a relative path (should save to path relative to the file).
- [x] Do the same but with an absolute path.
- [x] Do the same but on a different windows drive in the absolute path.
- [x] Open a new "untitled" file, change language mode to PowerShell and `Save()` (should not work)
- [x] Open a new "untitled" file, change language mode to PowerShell and `SaveAs()` with a relative path (should save relative to the workspace root).
- [x] Open a new "untitled" file, change language mode to PowerShell and `SaveAs()` to an absolute path.
- [x] Same as above but on a different windows drive.
- [x] ~~Open a new "untitled" workspace~~ Open VSCode with no workspace open, open an untitled document, change language mode to PowerShell and `SaveAs()` to an absolute path (should work).
- [x] Same as above but with a relative path (should not work, since ~~workspace is "untitled"~~ there is no workspace open).

### CODE REVIEW

File: src/features/ExtensionCommands.ts [hunk 1]
```diff
@@ -388,44 +389,106 @@ export class ExtensionCommandsFeature implements IFeature {
...
+                this.log.writeAndShowWarning("<ExtensionCommands>: " +
+                    `Unable to save file to path '${destinationAbsolutePath}': ${e}`);
+                return;
+            }
 
-        return EditorOperationResponse.Completed;
-   }
+            // Finally open the new document
+            const newFileUri = vscode.Uri.file(destinationAbsolutePath);
+            const newFile = await vscode.workspace.openTextDocument(newFileUri);
```
Comment (rkeithhill) [inline src/features/ExtensionCommands.ts]: Yea!  Glad to see some async/await make its way into the extension. I find it easier to read than a bunch of `.then()` continuations.  That's probably the C# dev in me coming out but I think TS/JS devs will like it too.

File: src/features/ExtensionCommands.ts [hunk 2]
```diff
@@ -388,44 +389,106 @@ export class ExtensionCommandsFeature implements IFeature {
...
+                }
+
+                await this.saveDocumentContentToAbsolutePath(currentFileUri, newFileAbsolutePath);
+                return EditorOperationResponse.Completed;
+
+            default:
+                // Other URI schemes are not supported
+                const msg = JSON.stringify(saveFileDetails);
+                this.log.writeVerbose(
+                    `<ExtensionCommands>: Saving a document with scheme '${currentFileUri.scheme}' ` +
```
Comment (rkeithhill) [inline src/features/ExtensionCommands.ts]: Try `<${ExtensionCommands.name}>: ... `

File: src/features/ExtensionCommands.ts [hunk 3]
```diff
@@ -388,44 +389,106 @@ export class ExtensionCommandsFeature implements IFeature {
...
+        destinationAbsolutePath: string): Promise<void> {
+            // Retrieve the text out of the current document
+            const oldDocument = await vscode.workspace.openTextDocument(documentUri);
+
+            // Write it to the new document path
+            try {
+                // TODO: Change this to be asyncronous
+                fs.writeFileSync(destinationAbsolutePath, oldDocument.getText());
+            } catch (e) {
+                this.log.writeAndShowWarning("<ExtensionCommands>: " +
```
Comment (rkeithhill) [inline src/features/ExtensionCommands.ts]: Ditto above comment

File: src/features/HelpCompletion.ts [hunk 4]
```diff
@@ -56,7 +56,8 @@ export class HelpCompletionFeature implements IFeature {
 
     public onEvent(changeEvent: TextDocumentChangeEvent): void {
         if (!(changeEvent && changeEvent.contentChanges)) {
-            this.log.write(`Bad TextDocumentChangeEvent message: ${JSON.stringify(changeEvent)}`);
+            this.log.writeWarning("<HelpCompletion>: " +
```
Comment (rkeithhill) [inline src/features/HelpCompletion.ts]: Try `<${HelpCompletion.name}>: ... `

File: src/features/ExtensionCommands.ts (hunk 2 above)
Comment (rjmholt) [reply src/features/ExtensionCommands.ts]: Ah nice!

File: src/features/ExtensionCommands.ts (hunk 1 above)
Comment (rjmholt) [reply src/features/ExtensionCommands.ts]: Yes, @SeeminglyScience set me on the right path there after I tried to put in a particularly twisted chain of `.then()`s when I first made this feature.

**Comment by rjmholt** [comment]
Oops, clicked the wrong button there.

**Comment by rjmholt** [comment]
@rkeithhill, I ended up having to put thinks like
```typescript
`<${ExtensionCommandsFeature.name}>`
```

My ideal would be to have some kind of `IFeature` extension method/convenience function that takes the type name and removes the `Feature` suffix, but I think that would basically require a macro to do nicely.

I'm assuming extension methods aren't a thing, particularly on interfaces, but we could maybe use a utility function. Ideally I can submit a new PR that improves extension logging.

File: src/features/ExtensionCommands.ts [hunk 5]
```diff
@@ -388,44 +390,106 @@ export class ExtensionCommandsFeature implements IFeature {
...
+                    return EditorOperationResponse.Completed;
+                }
+
+                // Make sure we have an absolute path
+                if (path.isAbsolute(saveFileDetails.newPath)) {
+                    newFileAbsolutePath = saveFileDetails.newPath;
+                } else {
+                    // If not, interpret the path as relative to the workspace root
+                    const workspaceRootUri = vscode.workspace.workspaceFolders[0].uri;
+                    // We don't saving to a non-file URI-schemed workspace
```
Comment (tylerl0706) [inline src/features/ExtensionCommands.ts]: nit pick: comment language:
"we don't saving" should be "we don't support saving"

File: src/features/ExtensionCommands.ts [hunk 6]
```diff
@@ -388,44 +390,106 @@ export class ExtensionCommandsFeature implements IFeature {
...
+                    if (workspaceRootUri.scheme !== "file") {
+                        return EditorOperationResponse.Completed;
+                    }
+                    newFileAbsolutePath = path.join(workspaceRootUri.fsPath, saveFileDetails.newPath);
+                }
+
+                await this.saveDocumentContentToAbsolutePath(currentFileUri, newFileAbsolutePath);
+                return EditorOperationResponse.Completed;
```
Comment (tylerl0706) [inline src/features/ExtensionCommands.ts]: nitpick, pull these two lines out of catch to be more DRY? ;)

File: src/features/ExtensionCommands.ts [hunk 7]
```diff
@@ -388,44 +390,106 @@ export class ExtensionCommandsFeature implements IFeature {
...
+    private async saveDocumentContentToAbsolutePath(
+        documentUri: vscode.Uri,
+        destinationAbsolutePath: string): Promise<void> {
+            // Retrieve the text out of the current document
+            const oldDocument = await vscode.workspace.openTextDocument(documentUri);
+
+            // Write it to the new document path
+            try {
+                // TODO: Change this to be asyncronous
+                fs.writeFileSync(destinationAbsolutePath, oldDocument.getText());
```
Comment (tylerl0706) [inline src/features/ExtensionCommands.ts]: Can we not already make this async? If it's too much work don't worry about it.

Synchronously make the file, asynchronously add the content to the file?

Comment (rjmholt) [reply src/features/ExtensionCommands.ts]: I looked into it, but `writeFile` is an older node API that wants a callback. I have been contemplating turning the whole call into a `Promise` though. Thoughts?

Comment (SeeminglyScience) [reply src/features/ExtensionCommands.ts]: Sorry if this is already known, but FYI you can await inline promises, e.g:

```typescript
await new Promise<void>((resolve) => {
    fs.writeFile(destinationAbsolutePath, oldDocument.getText(), resolve);
});
```

Comment (rjmholt) [reply src/features/ExtensionCommands.ts]: Ah that's handy! Thanks @SeeminglyScience

Comment (rjmholt) [reply src/features/ExtensionCommands.ts]: Type system wasn't quite happy with `resolve` there, but I've ended up with something similar.

**Comment by rjmholt** [comment]
Let me run the tests I've got above before we merge
