### PR TITLE
Change debugger type field back to "PowerShell" from powershell

### LINKED ISSUE #1768: Current master branch cannot debug PowerShell files
### System Details

System Details Output
```
### VSCode version: 1.32.0-insider aeaef41d51201e555735f5e8d2f38a9d0ddb9026 x64

### VSCode extensions:
bmaupin.theme-solarized-dark-high-contrast@1.0.2
clarkio.twitch-highlighter@0.1.3
CoenraadS.bracket-pair-colorizer-2@0.0.26
DavidAnson.vscode-markdownlint@0.24.0
eamodio.gitlens@9.5.1
EditorConfig.EditorConfig@0.13.0
eg2.tslint@1.0.43
Equinusocio.vsc-material-theme@2.7.0
ms-mssql.mssql@1.4.0
ms-vscode.csharp@1.17.1
ms-vscode.PowerShell-Preview@2.0.0
ms-vscode.vscode-typescript-tslint-plugin@1.0.0
msjsdiag.debugger-for-chrome@4.11.2
rrudi.vscode-dired@0.0.4
slevesque.vscode-autohotkey@0.2.2


### PSES version: 2.0.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.18836.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18836.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

I am experiencing a problem with debugging PowerShell scripts when building master after commit https://github.com/PowerShell/vscode-powershell/commit/f0886cd9edf58e12c612a209b77c5140740b9ecc

Steps I  have taken to reproduce issue:

1. clone PSES Master and vscode-powershell master to fresh directories
2. In vscode-powershell directory run: `git checkout f0886cd9edf58e12c612a2`
3. Launch Extension from vscode (stable or insiders)
4. Open a PowerShell file
5. Why can't I F5???

Note: F8 works just fine.

#### Expected Behaviour

It should debug the script

#### Actual Behaviour

It doesn't appear to do anything.

### Attached Logs

[1550730182-someValue.sessionId.zip](https://github.com/PowerShell/vscode-powershell/files/2887928/1550730182-someValue.sessionId.zip)

### PR DESCRIPTION
**Pull request by rkeithhill**
## PR Summary

This allows the debugger to start but not sure why (lower-case) "powershell" doesn't
work. That said, the previous change meant that users would have to
update their launch.json to change the type to "powershell".  But
even when I do that, the debugger still doesn't launch. So I'm a bit
puzzled.  But this gets the debugger working again on master.

Also fixed some warnings in session.ts.

Fix #1768

## PR Checklist

Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] PR has tests
- [x] This PR is ready to merge and is not work in progress
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready

### CODE REVIEW

File: src/session.ts [hunk 1]
```diff
@@ -411,8 +411,9 @@ export class SessionManager implements Middleware {
         if (!this.suppressRestartPrompt &&
             (settings.useX86Host !== this.sessionSettings.useX86Host ||
              settings.powerShellExePath.toLowerCase() !== this.sessionSettings.powerShellExePath.toLowerCase() ||
-             settings.developer.powerShellExePath.toLowerCase() !==
-                this.sessionSettings.developer.powerShellExePath.toLowerCase() ||
+             (settings.developer.powerShellExePath ? settings.developer.powerShellExePath.toLowerCase() : null) !==
```
Comment (rkeithhill) [inline src/session.ts]: I really wish TypeScript had C# `?!` operator.

**Comment by TylerLeonhardt** [comment]
I think this PR forgot these:
https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L458-L501
